import Head from 'next/head';
import Link from 'next/link';
import GradientGenerator from './GradientGenerator';


export default function Home() {
  return (
    <>
      <Head>
        <title>Gradient Generator | by @NickDevCode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="min-h-screen w-screen bg-white flex justify-center items-center">
        <div className="">
          <GradientGenerator />
        </div>
      </section>

    </>
  )
}
